from .advertisement_create import (
    ADVERTISEMENT_CREATE_MEDIA_INPUT_MARKUP,
    ADVERTISEMENT_CREATE_SPECIFIC_MEDIA_MARKUP,
    ADVERTISEMENT_CREATE_TEXT_INPUT_MARKUP,
)
from .user_menu import USER_MENU_MARKUP
from .user_register import (
    USER_REGISTER_CONFIRM_MARKUP,
    USER_REGISTER_FLOW_START_MARKUP,
    USER_REGISTER_PHONE_NUMBER_INPUT_MARKUP,
)

__all__ = (
    "USER_MENU_MARKUP",
    "USER_REGISTER_FLOW_START_MARKUP",
    "USER_REGISTER_PHONE_NUMBER_INPUT_MARKUP",
    "USER_REGISTER_CONFIRM_MARKUP",
    "ADVERTISEMENT_CREATE_TEXT_INPUT_MARKUP",
    "ADVERTISEMENT_CREATE_MEDIA_INPUT_MARKUP",
    "ADVERTISEMENT_CREATE_SPECIFIC_MEDIA_MARKUP",
)
